### ISSUE TITLE
[Bug] CatServer未成功将MCP类转换为Spigot类

### ISSUE THREAD

**Issue by windy664** [0XPYEX0/CnUsername#3]
```[22:55:39] [Server thread/INFO]: [AnyUsername] Enabling AnyUsername v1.0.0
[22:55:39] [Server thread/INFO]: [22:55:39 INFO]: [CnUsername] 已加载
[22:55:39] [Server thread/INFO]: [22:55:39 INFO]: [CnUsername] 如遇Bug，或需提出建议: QQ1723275529
[22:55:39] [Server thread/INFO]: [22:55:39 INFO]: [CnUsername] 开始修改类 net.minecraft.server.network.LoginListener
[22:55:39] [Server thread/INFO]: java.io.IOException: Class not found
[22:55:39] [Server thread/INFO]:        at %{project.group}.libs.asm.ClassReader.readStream(ClassReader.java:315)
[22:55:39] [Server thread/INFO]:        at %{project.group}.libs.asm.ClassReader.<init>(ClassReader.java:287)
[22:55:39] [Server thread/INFO]:        at me.xpyex.plugin.cnusername.bukkit.CnUsernameBK.onEnable(CnUsernameBK.java:54)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/forge@40.2.4/org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/forge@40.2.4/org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:351)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/forge@40.2.4/org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/forge@40.2.4/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugin(CraftServer.java:423)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/forge@40.2.4/org.bukkit.craftbukkit.v1_18_R2.CraftServer.enablePlugins(CraftServer.java:349)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_129815_(MinecraftServer.java:499)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130006_(MinecraftServer.java:372)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.dedicated.DedicatedServer.m_7038_(DedicatedServer.java:240)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:913)
[22:55:39] [Server thread/INFO]:        at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:312)
[22:55:39] [Server thread/INFO]:        at java.base/java.lang.Thread.run(Thread.java:833)
[22:55:39] [Server thread/INFO]: [22:55:39 WARN]: [CnUsername] 修改失败
```

**Comment by 0XPYEX0** [comment]
混合端nms映射与纯Bukkit端不同，无法完全兼容
等我有空看看，无法兼容也没办法了
